export const customerDataMock = {
  id: '12',
  salutation: 'Ms.',
  initials: 'C.N.',
  firstname: 'Cheri',
  firstname_ascii: 'cheri',
  gender: 'f',
  firstname_country_rank: '588',
  firstname_country_frequency: '316',
  lastname: 'Leitner',
  lastname_ascii: 'leitner',
  lastname_country_rank: '9587',
  lastname_country_frequency: '36',
  email: 'c.leitner@verizon.net',
  password: 'CL87-dKltzI!',
  country_code: 'US',
  country_code_alpha: 'USA',
  country_name: 'United States',
  primary_language_code: 'en',
  primary_language: 'English',
  balance: 79.27,
  phone_Number: '+1 518-531-9140',
  currency: 'USD',
  partitionKey: 'US',
  rowKey: '12',
  timestamp: '2023-12-14T13:17:50.6705415+00:00',
  eTag: {},
};
